# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.cache/wt [current_project]
set_property parent.project_path /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/decoder.vhd
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/roshambo_logic.vhd
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/mux.vhd
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/debouncer.vhd
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/clk.vhd
  /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/sources_1/new/Ro_sham_bo.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/constrs_1/new/Ro_sham_bo.xdc
set_property used_in_implementation false [get_files /home/aaron/school/EGR426/Ro_sham_bo/Ro_sham_bo.srcs/constrs_1/new/Ro_sham_bo.xdc]


synth_design -top seven_seg -part xc7a35tcpg236-1


write_checkpoint -force -noxdef seven_seg.dcp

catch { report_utilization -file seven_seg_utilization_synth.rpt -pb seven_seg_utilization_synth.pb }
